Loading/Creating Databases
```{r}
{
Champions <- read.csv("champions_stats.csv")
Matchs <- read.csv("matchs_stats.csv")
Player <- read.csv("players_stats.csv")
}
{
Current_Players <- data.frame("LPL","JD_Gaming","365","Kanavi","Knight","Ruler","Missing")
Current_Players[2,] <- c("LPL","Bilibili_Gaming","Bin","Xun","Yagao","Elk","ON")
Current_Players[3,] <- c("LPL","LNG_Esports","Zika","Tarzan","Scout","Gala","Hang")
Current_Players[4,] <- c("LPL","WB_Gaming","TheShy","Weiwei","Xiaohu","Light","Crisp")
Current_Players[5,] <- c("LCK","Gen_g","Doran","Peanut","Chovy","Peyz","Delight")
Current_Players[6,] <- c("LCK","T1","Zeus","Oner","Faker","Gumayusi","Keria") #They were previously known as sktt1.
Current_Players[7,] <- c("LCK","KT_Rolster","Kiin","Cuzz","Bdd","Aiming","Lehends")
Current_Players[8,] <- c("LCK","Dplus_KIA","Canna","Canyon","ShowMaker","Deft","Kellin") #They were previously known as DAMWON Gaming and DWG KIA.
Current_Players[9,] <- c("LEC","G2_Esports","BrokenBlade","Yike","Caps","Hans Sama","Mikyx") 
Current_Players[10,] <- c("LEC","Fnatic","Oscarinin","Razork","Humanoid","Noah","Trymbi")
Current_Players[11,] <- c("LEC","MAD_Lions","Chasy","Elyoya","Nisqy","Carzzy","Hylissang") 
Current_Players[12,] <- c("LEC","BDS","Adam","Sheo","Nuc","Crownie","Labrov") 
Current_Players[13,] <- c("LCS","NRG","Dhokla","Contractz","Palafox","FBI","Ignar")
Current_Players[14,] <- c("LCS","Cloud9","Fudgr","Blaber","EMENES","Berserker","Zven")
Current_Players[15,] <- c("LCS","Team_Liquid","Summit","Pyosik","APA","Yeon","CoreJJ") 
Current_Players[16,] <- c("LCS","Golden_Guardians","Licorice","River","Gori","Sitxxay","Huhi")
Current_Players[17,] <- c("PCS","PSG_Talon","Azhi","Junjia","Maple","Wako","Woody")
Current_Players[18,] <- c("PCS","CTBC_Flying_Oyster","Rest","Gemini","JimieN","Shunn","ShiauC") 
Current_Players[19,] <- c("VCS","GAM_Esports","Kiaya","Levi","Kati","Slayder","Palette")
Current_Players[20,] <- c("VCS","Whales","Sparda","BeanJ","Glory","Artemis","Bie")
Current_Players[19,] <- c("CBLOL","LOUD","Robo","Croc","Tinowns","Route","Ceos")
Current_Players[20,] <- c("LJL","DetonatioN_FocusMe","Yutapon","Steal","Aria","Milan","Harp")
Current_Players[21,] <- c("LLA","Movistar_R7","Bong","Oddie","Mireu","Ceo","Lyonz")
colnames(Current_Players)<- c("Region","Team","Top","Jungle","Mid","Adc","Supporte")
}

```

Exploratory analisis
```{r}
str(Champions)
table(Champions$season)
# Season 1:12, as season começaram em 2011 juntamente com os torneios
table(Champions$event)
# Play in são jogos classificatórios, main é o "real" torneio
table(Champions$champion)
# não aparenta ter nenhum nome escrito de formas diferentes
# games_contest é a coluna que informa o número de jogos que aquele personagem foi banido/usado em jogo
# Todas as outras colunas são bem intuitivas e não apresentam nenhum erro
# existem alguns valores NA nas ultimas colunas...
str(Matchs)
# patch são atualizações mensais que fazem no jogo.
# os primeiros elementos da coluna patch, tem valores NA pois antigamente não faziam essas atualizações no jogo.
table(Matchs$blue_team)
# é importante ter atenção no nome dos times pois alguns trocaram de nome, mas represantam a mesma coisa;
# ex: SK_Telecom_T1 == T1, DWG_KIA == Dplus_KIA,  Gen_g == Gen_2e-G == KSV eSports e etc...
# uma maneira possível de descobrir os times com nomes diferentes seria comparar com os times que estão competindo atualmente para ver se tem algum nome diferente
# a maioria dos jogadores afirmam que no time azul existe a maior taxa de vitória, seria legal analisar isso.
# o resto é lista dos personagens e players que jogaram.
str(Player)
# mesma ideia do tratamento de times
table(Player$player) # fazer verificação de nomes com os nomes em cenário atual
Player$teste <- ifelse(Player$wins + Player$loses ==Player$games_played,0,1) # teste para verificar se tinha alguma quantidade errada de jogos/vitorias/derrotas.
# essas outras colunas de desempenho do jogador podem servir para criarmos uma métrica de avaliação para os jogadores.



```
Treating data
```{r}
sum(Matchs[,5:7] == "SK_Telecom_T1")
{
Matchs$blue_team <- ifelse(Matchs$blue_team == "SK_Telecom_T1","T1",Matchs$blue_team)
Matchs$red_team <- ifelse(Matchs$red_team == "SK_Telecom_T1","T1",Matchs$red_team)
Matchs$winner <- ifelse(Matchs$winner == "SK_Telecom_T1","T1",Matchs$winner)}

sum(Matchs[,5:7] == "Gen_2e-G")
{
Matchs$blue_team <- ifelse(Matchs$blue_team == "Gen_2e-G","Gen_g",Matchs$blue_team)
Matchs$red_team <- ifelse(Matchs$red_team == "Gen_2e-G","Gen_g",Matchs$red_team)
Matchs$winner <- ifelse(Matchs$winner == "Gen_2e-G","Gen_g",Matchs$winner)}

sum(Matchs[,5:7] == "DWG_KIA")
{
Matchs$blue_team <- ifelse(Matchs$blue_team == "DWG_KIA","Dplus_KIA",Matchs$blue_team)
Matchs$red_team <- ifelse(Matchs$red_team == "DWG_KIA","Dplus_KIA",Matchs$red_team)
Matchs$winner <- ifelse(Matchs$winner == "DWG_KIA","Dplus_KIA",Matchs$winner)}
{
Player$team <- ifelse(Player$team == "SK_Telecom_T1","T1",Player$team)
Player$team <- ifelse(Player$team == "Gen_2e-G","Gen_g",Player$team)
Player$team <- ifelse(Player$team == "DWG_KIA","Dplus_KIA",Player$team)
}
```


Manipulating data

```{r}
# O campeao mais jogado de cada mundial
library(tidyverse)
Frequency_champions <- Champions %>%
  group_by(season, event) %>%
  summarise(
    games = max(games_contests)
  ) %>%
  ungroup() %>%
  left_join(Champions, by = c("season", "event", "games" = "games_contests"))%>%
  filter(event == "Main")
head(Frequency_champions,12)

# Os campeoes mais disputados no utimo ano
LastYear_champions <- Champions %>%
  filter(season == 12 & event == "Main" ) %>%
  arrange(-pick_ban_ratio)
head(LastYear_champions)

# Os com maior taxa de vitória
LastYear_winrate <- LastYear_champions %>%
  arrange(-win_rate)
head(LastYear_winrate)

# conseguimos saber qual time mais ganhou
Winners <- Matchs %>%
  group_by(winner,event) %>%
  summarise(
    games = n()
  )%>%
  arrange(-games)

# qual time mais ganhou em cada temporada
Season_Winners <- Matchs %>%
  group_by(season,winner,event) %>%
  summarise(
    games = n()
  )%>%
  arrange(season,-games)

# não tinha na base de dados os respectivos ganhadores de cada mundial.
# 2011	 Fnatic	2–1	 against All authority	Elmia	Jönköping, Suécia
# 2012	 Taipei Assassins	3–1	 Azubu Frost	Galen Center	Los Angeles, Estados Unidos
# 2013	 SK Telecom T1	3–0	 Royal Club	Staples Center	Los Angeles, Estados Unidos
# 2014	 Samsung White	3–1	 Star Horn Royal Club	Seoul World Cup Stadium	Seul, Coreia do Sul
# 2015	 SK Telecom T1	3–1	 KOO Tigers	Mercedes-Benz Arena	Berlim, Alemanha
# 2016	 SK Telecom T1	3–2	 Samsung Galaxy	Staples Center	Los Angeles, Estados Unidos
# 2017	 Samsung Galaxy	3–0	 SK Telecom T1	Beijing National Stadium	Pequim, China
# 2018	 Invictus Gaming	3–0	 Fnatic	Incheon Munhak Stadium	Incheon, Coreia do Sul
# 2019	 FunPlus Phoenix	3–0	 G2 Esports	AccorHotels Arena	Paris, França
# 2020	 Damwon Gaming	3–1	 Suning	Pudong Football Stadium	Xangai, China
# 2021	 Edward Gaming	3–2	 DWG KIA	Laugardalshöll	Reiquiavique, Islândia
# 2022	 DRX 3–2	Coreia do Sul T1	Chase Center	São Francisco, Estados Unidos

ScoreBoard <- Matchs %>%
  group_by(blue_team,red_team) %>%
  summarise(
    blue_win = sum(winner == blue_team),
    red_win = sum(winner == red_team)
  )# queria fazer um melhor

# comparação dos lados azul e vermelho
sum(ScoreBoard$blue_win)
sum(ScoreBoard$red_win)
Percent_blue <- sum(ScoreBoard$blue_win)/(sum(ScoreBoard$blue_win)+sum(ScoreBoard$red_win))


```

